# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-29 15:00
from __future__ import unicode_literals

import content.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('teacher_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('school_class', models.IntegerField(choices=[(1, '1UID-1'), (2, '1UID-2'), (3, '2UID-3'), (4, '2UID-4')])),
                ('year_of_birth', models.IntegerField(null=True, validators=[content.validators.validate_year_length, content.validators.validate_year_of_birth])),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(3, '3'), (3.5, '3+'), (4, '4'), (4.5, '4+'), (5, '5')])),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SchoolSubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Student')),
            ],
            options={
                'permissions': [('see_studentgrades', 'Can see students grades')],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.ManyToManyField(through='content.StudentGrades', to='content.SchoolSubject'),
        ),
    ]
