# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-29 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180129_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='grade',
            field=models.FloatField(choices=[(3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5')]),
        ),
    ]
